### ISSUE TITLE
Interpolated css blocks

### ISSUE THREAD

**Issue by Jmeyering** [styled-components/stylelint-config-styled-components#18]
As you can see, interpolated css blocks within a styled component trigger a 

```
Expected single space before "{" (block-opening-backtick-space-before) [block-opening-brace-space-before]
```
Not sure what I'm doing incorrectly. I tried to follow the indentation rules specified on the SC website.

![image](https://user-images.githubusercontent.com/5166603/30661825-c04c6394-9e0a-11e7-8533-579914a94809.png)

**Comment by Jmeyering** [comment]
This potentially is an isolated example. This happens to be a third party component that we are exposing, and we have a lot of nesting going on in this file. I'm going to close this for now and consider this a fluke. If you are interested I can post the full text of the component.

**Comment by mxstbr** [comment]
It'd be awesome if you could add the full text as a real world test case in a PR! :100:
